--DROP TABLE cw_appointments IF EXISTS;

CREATE TABLE cw_appointments (
  cw_appointments_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  cw_id BIGINT,
  organizer VARCHAR(50),
  subject VARCHAR(100),
  location VARCHAR(100),
  start_date VARCHAR(20),
  start_time VARCHAR(20),
  duration VARCHAR(20)
);