$(document).ready(function(){
	$('#mySpinner').removeClass('spinner');
	$('#mySpinnerBackdrop').removeClass('show');
	$('#mySpinnerBackdrop').addClass('hide');
	$('#getStarted').on('click',function(){
		$('#mySpinner').addClass('spinner');
		$('#mySpinnerBackdrop').removeClass('hide');
		$('#mySpinnerBackdrop').addClass('show');
	});			
});	